name: runTestsForReleaseBuild

on:
    push:
        branches: [ main ]

jobs:
    runTestsForReleaseBuild:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: "Create build directory"
              run: mkdir build
            - name: "Run CMake"
              working-directory: build
              run: cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ..
            - name: "Run Make"
              working-directory: build
              run: make VERBOSE=1
            - name: "Run tests"
              working-directory: build
              run: make test
