name: tryCompilersAndGenerateCoverageReport

on:
    push:
        branches:
          - main
          - master
          - develop
          - feature/*

jobs:
    tryClangOnUbuntu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: "Compile with clang++"
              run: clang++ -std=c++17 -Wall -Wextra -pedantic -O0 tests.cpp CustomClass/customClass.cpp
            - name: "Run tests"
              run: ./a.out

    tryClOnWindows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ilammy/msvc-dev-cmd@v1
            - name: "Compile with cl"
              run: cl /std:c++17 /EHsc /Wall tests.cpp CustomClass/customClass.cpp
            - name: "Run tests"
              run: ./tests.exe

    tryGCCOnUbuntuAndGenerateCoverageReport:
        needs: tryClangOnUbuntu
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: "Compile with g++"
              run: g++ -std=c++17 -g -Wall -Wextra -pedantic --coverage tests.cpp CustomClass/customClass.cpp
            - name: "Run program to generate .gcda file"
              run: ./a.out
            - name: "Make coverage report directory"
              run: mkdir coverage
            - name: 'Install lcov'
              run: sudo apt-get -y install lcov
            - name: "Run lcov"
              run:  lcov --capture --directory . --output-file coverage/coverage.info
            - name: "Run genhtml"
              run: genhtml --output-directory coverage/coverage-html --legend coverage/coverage.info
            - name: "Save coverage report artifact"
              uses: actions/upload-artifact@v2
              with: 
                name: code-coverage-report
                path: coverage
                retention-days: 1